name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  
  # --- Core Data & Machine Learning ---
  - pandas
  - numpy
  - scikit-learn
  - scipy
  - matplotlib
  
  # --- Web Scraping & Networking ---
  - requests
  - beautifulsoup4
  - scrapy
  - w3lib
  
  # --- Testing ---
  - pytest
  - flake8
